server:
  port: 1111

spring:
    profiles:
      active: dev

mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.lanyu.common.model


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#thymeleaf 开发时关闭缓存,不然没法看到实时页面
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  cache: false

#配置日志
logging:
  #配置日志文件路径
  level:
    com.lanyu.admin.mapper: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log



