banner:
  location: config/banner.txt
  encoding: utf-8
server:
  servlet:
    context-path: /
  session-timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  port: 8088
  uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  application:
    name: ifast
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
#     mode: LEGACYHTML5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      WRITE_NUMBERS_AS_STRINGS: true    
  profiles:
    active: @activatedProperties@
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  redis:
   host: 127.0.0.1
   port: 6379
   password: 123456
   database: 2
  devtools:
    restart:
      enabled: true

# mybatis:
#     typeHandlersPackage:      

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.ifast.**.domain
  global-config:
    refresh: true
    id-type: 2
    field-strategy: 1
    db-column-underline: true
    capital-mode: false
#     sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
    logic-not-delete-value: 1
    logic-delete-value: -1
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
